name       : liboobs
version    : 3.0.0
release    : 2
source     :
    - http://ftp.gnome.org/pub/GNOME/sources/liboobs/3.0/liboobs-3.0.0.tar.gz : cb962632cc00dad7770a34176a0fa5e553b16e7fa4660ff3648121f0940b0fba
license    : GPL-2.0
component  : desktop.mate
summary    : Wrapper library for System Tools Backends
builddeps  :
    - pkgconfig(dbus-glib-1)
    - pkgconfig(system-tools-backends-2.0)
description: |
    Wrapper library for System Tools Backends
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
